apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: smarthpa-ui
    app.kubernetes.io/name: smarthpa-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: smarthpa
spec:
  type: ClusterIP
  selector:
    app: smarthpa-ui
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
---
# NodePort Service (optional - for direct node access)
apiVersion: v1
kind: Service
metadata:
  name: ui-nodeport
  labels:
    app: smarthpa-ui
    app.kubernetes.io/name: smarthpa-ui
    app.kubernetes.io/component: ui
spec:
  type: NodePort
  selector:
    app: smarthpa-ui
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30090
    protocol: TCP

